wiseclinic:
  database:
    paciente: "files/paciente.json"
    dentista: "files/dentista.json"
    consulta-medica: "files/consulta-medica.json"
    consulta-odontologica: "files/consulta-odontologica.json"
    medico: "files/medico.json"